Updated the previous PR #247
socialincome-san/public pull request #258
Opened 2023-01-16 12:06 UTC by soumdatta81

**Added React functional component called DataList in /ui package and implemented server-side Firestore data retrieval with getStaticProps.**

2023-01-16 15:51 UTC, ssandino commented
Thanks @soumdatta81 

@renestalder everyone with our Vercel credentials can authorize the deployment (this just changed yesterday, as we had to made changes to our Vercel account). I assume this is momentarily (@andrashee knows more)

I authorised it, however the deployment failed for following reason (you can also click above in the checks to see that): 
<img width="883" alt="Screenshot 2023-01-16 at 16 44 36" src="https://user-images.githubusercontent.com/6095849/212717963-fcf8cf0a-a688-4633-aebd-c97cc29eb2cc.png">

2023-01-16 16:03 UTC, renestalder requested changes
That's a good start. There are a couple of changes that are needed:

1. Move the component from `ui/datalist.jsx` to `ui/src/components/datalist/Datalist.tsx` (use tsx and PascalCase for naming the component file).
2. Add proper TypeScript types for the component parameter, so there are easier to use. Check other components, like the [button component](https://github.com/socialincome-san/public/blob/main/ui/src/components/button/Button.tsx), for an example of how that works.
3. Prefix the component's name with `So` e.g. `SoDataList` to ensure we don't have a clash with the native HTMLDataListElement.
4. Add a Storybook Story to the same folder with the component to ensure this component is documented. See also the button component and [`button.stories.tsx`](https://github.com/socialincome-san/public/blob/main/ui/src/components/button/Button.stories.tsx) for an example of how that works.

2023-01-16 16:08 UTC, renestalder requested changes

2023-01-16 16:08 UTC, renestalder commented on ui/datalist.jsx
> +const DataList = ({data}) => {
Add prefix and export:

```suggestion
export const SoDataList = ({data}) => {
```

2023-01-16 16:08 UTC, renestalder commented on ui/datalist.jsx
> +export default DataList;
Remove `default` export. We want to embrace export barrels, and default exports make this more difficult to maintain.

```suggestion
```

2023-01-17 19:59 UTC, soumdatta81 commented
I am unsure of how to properly and where to connect the data list to the Firebase production collection. Can you please provide guidance or assistance in this matter?

2023-01-18 18:56 UTC, soumdatta81 commented
Some changes were made with #262 and #263. I hope these will work.

2023-01-31 21:21 UTC, closed without merging