Feat/731 navigation
socialincome-san/public pull request #770
Opened 2024-03-10 20:43 UTC by svrmnk

At this pull, I fixed the bug with transparency sub-items, but I am stuck with the popup of languages.

I consider, that this solition is the most suitable, when JS is crashed or disabled:
add "id" to popup component, than make button by tag with href="id" and using css pseudo-class :target to add styles at popup.

Will this solution suit?

2024-03-25 09:38 UTC, renestalder requested changes
@svrmnk Thank you so much for your contribution.

I don't think we are right there in terms of the right solution. While this works great without JavaScript, it removes all the ARIA-handling for screenreader users. Furthermore, the navigation can't be opened with the keyboard anymore.

We have to make sure that:

- Opening the navigation is properly announced to assistive technology. That involves using the correct aria attributes to mark what element the button is controlling and whether it is expanded/pressed. Until now, the popover components handled this. Due to removing these, those aria handlers are missing.
- That I can open it with the keyboard.

2024-03-26 17:04 UTC, svrmnk commented on website/src/components/navbar/navbar-client.tsx
> +											<div key={index} className="group relative">
I've added ability to open the submenu using the keyboard, but I don't know which ARIA was added via popover before this. So, I suggest my solition as it is now. Your team or others contributers will be able to add the required ARIA in the future or in this pull request.

2024-04-03 18:09 UTC, svrmnk commented on website/src/components/navbar/navbar-client.tsx
> +											<div key={index} className="group relative">
@renestalder, could you please give feedback? Can we solve the problem with ARIA attributes in the following tasks? And now focus on the work of menu elements without JS in this task?

Or could yo describe in detail what needs to be done, which ARIA attributes need to be added in order for the result to satisfy you?

2024-04-15 09:35 UTC, svrmnk commented on website/src/components/navbar/navbar-client.tsx
> +											<div key={index} className="group relative">
@renestalder, hey, could you give some feedback?

2024-04-23 11:18 UTC, closed without merging